set PYTHONOPTIMIZE=1 && pyinstaller --noconfirm --log-level=WARN ^
    --clean ^
    --hidden-import=pygame ^
    --hidden-import=log-color ^
    --hidden-import=six ^
    --hidden-import=toml ^
    --hidden-import=boltons ^
    -p src\harren ^
    --add-data=src\harren;harren ^
    --name=harren ^
    --onefile ^
    --noconsole
